name: Flutter

on:
  push:
    branches: [ "master","main" ]
  pull_request:
    branches: [ "master","main" ]

jobs:
  flutter_job:
    
    runs-on: macos-latest

    steps:

      
      - uses: actions/checkout@v4